import type { Metadata } from "next"; 
import "@/styles/globals.css"; 
import NavBar from "@/components/nav-bar";
 

export const metadata: Metadata = {
  title: "Zeo API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex-1 flex flex-col">
      <NavBar/>
      {children}
    </div>
 
  );
}
